name: Build Nova Optimizer

on:

push:

branches: [ main ]

workflow_dispatch:

jobs:

build:

runs-on: windows-latest

steps:

uses: actions/checkout@v4

uses: actions/setup-dotnet@v4

with:

dotnet-version: '8.0.x'

name: Restore

run: dotnet restore Novaoptimiz

name: Publish

run: dotnet publish Novaoptimiz

name: Upload

uses: actions/upload-artifact@v

with:

name: NovaOptimizer-EXE

path: ./output/Nova0ptimizer.
